export {default as App} from './App/App.jsx';
export {default as Art} from './Art/Art.jsx';
export {default as Home} from './Home/Home.jsx';
export {default as Signup} from './Signup/Signup.jsx';
export {default as Login} from './Login/Login.jsx';
export {default as MyCollection} from './MyCollection/MyCollection.jsx';
export {default as NotFound} from './NotFound/NotFound.jsx';
export {default as DevTools} from './DevTools/DevTools.jsx';
export {default as UserProfile} from './UserProfile/UserProfile.jsx';
