const mongoose = require('mongoose');
mongoose.Promise = global.Promise;
const ObjectId = mongoose.Schema.ObjectId;

// // starting the name with an underscore is simply a convention
// // to denote this field as a reference
// // the type instructs Mongoose to set this up as a reference
// // to another document's _id property, which is automatically
// // generated by MongoDB. the ref field refers to the Model name
// _food: { type: Schema.Types.ObjectId, ref: 'Food' }
const artSchema = mongoose.Schema({

	picture: String,
	title: String,
    author: String,
	desc: String,

	dateReg: {
		type: Date,
		default: Date.now
	},

    likes: [
        {
            type: ObjectId,
            ref: 'User'
        }
    ],

    comments: [
        {
            author: {
                type: ObjectId,
                ref: 'User'
            },
            content: String,
            date: {
                type: Date,
                default: Date.now
            }
        }
    ]

});

//compile
module.exports = mongoose.model('Art', artSchema);
